name: Unzip Dropee

on:
  push:
    paths:
      - 'dropee.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip uploaded file
        run: |
          unzip -o dropee.zip -d .
          rm dropee.zip

      - name: Push unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped dropee.zip"
          git push
          
